haproxy:
  image: tutum/haproxy
  links:
    - node
  ports:
    - "1936:1936"
    - "80:80"
node:
  build: ./sloth
  expose: 
    - 3000
  links:
    - mongo
mongo:
  image: mongo
  expose: 
    - 27017

