nginx:
  image: jwilder/nginx-proxy
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock:ro"
  ports:
  - "80:80"
app:
  build: .
  environment:
  - VIRTUAL_HOST=slothracing.com
  ports:
  - "3000"
  links:
  - mongo
mongo:
  image: mongo
  expose: 
    - 27017
